name: Update Followers

on:
  schedule:
    - cron: '5 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_followers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch latest followers
      run: |
        curl -s "https://api.github.com/users/hu8813/followers" > followers.json
        jq -r '.[0:5] | .[] | "![\(.login)](https://github.com/\(.login)) ![\(.login)](https://github.com/\(.login).png)"' followers.json > followers.md

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add followers.md
        git commit -m "Update latest followers"
        git push
