name: Update Weather Badge

on:
  schedule:
    - cron: '27 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch weather data
      run: |
        curl -s "https://api.openweathermap.org/data/2.5/weather?q=Vienna&appid=${{ secrets.OPENWEATHERMAP_API_KEY }}&units=metric" | jq -r '"Temperature: " + (.main.temp | tostring) + "°C" + " - " + .weather[0].description' > weather.txt

    - name: Create weather badge
      run: |
        WEATHER=$(cat weather.txt)
        echo "<svg xmlns='http://www.w3.org/2000/svg' width='300' height='60'><rect width='100%' height='100%' fill='#555'/><rect x='70' width='80' height='20' fill='#007ec6'/><rect rx='3' width='150' height='20' fill='transparent'/><g fill='#fff' text-anchor='middle' font-family='Verdana' font-size='110'><text x='35' y='140' transform='scale(.1)' fill='#fff'>Weather</text><text x='110' y='140' transform='scale(.1)' fill='#fff'>${WEATHER}</text></g></svg>" > weather_badge.svg

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add weather_badge.svg
        git commit -m "Update weather badge"
        git push
