name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '46 * * * *'  # Runs every hour

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read followers file
      id: read_followers
      run: |
        echo "content<<EOF" >> $GITHUB_ENV
        cat followers.md >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Update README
      run: |
        followers_content="${{ env.content }}"
        sed -i.bak -e '/<!-- FOLLOWERS:START -->/,/<!-- FOLLOWERS:END -->/c\
        <!-- FOLLOWERS:START -->\n'"$followers_content"'\n<!-- FOLLOWERS:END -->' README.md

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "Update latest followers in README"
        git push
